name: certificate_gen
description: A new Flutter project.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  certify_me: ^0.1.2
  path: ^1.8.3
  path_provider: ^2.1.1
  intl: ^0.18.1
  url_launcher: ^6.2.4
  flutter_pdfview: ^1.2.5
  http: ^0.13.6
  cupertino_icons: ^1.0.8
  file_picker: ^10.2.0
  google_ml_kit: ^0.20.0
  image: ^4.0.17
  google_mlkit_text_recognition: ^0.15.0
  syncfusion_flutter_pdf: ^24.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
